// Code generated by "stringer -type=ConditionType"; DO NOT EDIT.

package messages

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HP-1]
	_ = x[Floor-2]
	_ = x[AvailableFood-3]
}

const _ConditionType_name = "HPFloorAvailableFood"

var _ConditionType_index = [...]uint8{0, 2, 7, 20}

func (i ConditionType) String() string {
	i -= 1
	if i < 0 || i >= ConditionType(len(_ConditionType_index)-1) {
		return "ConditionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ConditionType_name[_ConditionType_index[i]:_ConditionType_index[i+1]]
}
