// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package messages

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AskFoodTaken-1]
	_ = x[AskHP-2]
	_ = x[AskFoodOnPlatform-3]
	_ = x[AskIntendedFoodIntake-4]
	_ = x[StateFoodTaken-5]
	_ = x[StateHP-6]
	_ = x[StateFoodOnPlatform-7]
	_ = x[StateIntendedFoodIntake-8]
	_ = x[StateResponse-9]
	_ = x[ProposeTreaty-10]
	_ = x[RequestLeaveFood-11]
	_ = x[RequestTakeFood-12]
	_ = x[Response-13]
	_ = x[TreatyResponse-14]
}

const _MessageType_name = "AskFoodTakenAskHPAskFoodOnPlatformAskIntendedFoodIntakeStateFoodTakenStateHPStateFoodOnPlatformStateIntendedFoodIntakeStateResponseProposeTreatyRequestLeaveFoodRequestTakeFoodResponseTreatyResponse"

var _MessageType_index = [...]uint8{0, 12, 17, 34, 55, 69, 76, 95, 118, 131, 144, 160, 175, 183, 197}

func (i MessageType) String() string {
	i -= 1
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
