// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package messages

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AskFoodTaken-1]
	_ = x[AskHP-2]
	_ = x[AskIntendedFoodIntake-3]
	_ = x[StateFoodTaken-4]
	_ = x[StateHP-5]
	_ = x[StateIntendedFoodIntake-6]
	_ = x[StateResponse-7]
	_ = x[ProposeTreaty-8]
	_ = x[RequestLeaveFood-9]
	_ = x[RequestTakeFood-10]
	_ = x[Response-11]
	_ = x[TreatyResponse-12]
}

const _MessageType_name = "AskFoodTakenAskHPAskIntendedFoodIntakeStateFoodTakenStateHPStateIntendedFoodIntakeStateResponseProposeTreatyRequestLeaveFoodRequestTakeFoodResponseTreatyResponse"

var _MessageType_index = [...]uint8{0, 12, 17, 38, 52, 59, 82, 95, 108, 124, 139, 147, 161}

func (i MessageType) String() string {
	i -= 1
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
