// Code generated by "stringer -type=Op"; DO NOT EDIT.

package messages

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GT-1]
	_ = x[GE-2]
	_ = x[EQ-3]
	_ = x[LE-4]
	_ = x[LT-5]
}

const _Op_name = "GTGEEQLELT"

var _Op_index = [...]uint8{0, 2, 4, 6, 8, 10}

func (i Op) String() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
