// Code generated by "stringer -type=RequestType"; DO NOT EDIT.

package messages

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeaveAmountFood-1]
	_ = x[LeavePercentFood-2]
	_ = x[Inform-3]
}

const _RequestType_name = "LeaveAmountFoodLeavePercentFoodInform"

var _RequestType_index = [...]uint8{0, 15, 31, 37}

func (i RequestType) String() string {
	i -= 1
	if i < 0 || i >= RequestType(len(_RequestType_index)-1) {
		return "RequestType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RequestType_name[_RequestType_index[i]:_RequestType_index[i+1]]
}
